server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://order-postgres:5432/order_db
    username: order_service
    password: order_password
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

app:
  order:
    max-items-per-order: 10
    auto-cancel-timeout: 1800
